### ISSUE TITLE
Stack Trace If CWD Is Root

### ISSUE THREAD

**Issue by rgajason** [GitGuardian/gg-shield#52]
Executing `ggshield` from the root of a Unix/Linux filesystem results in the following stack trace:

```
$ cd /
$ ggshield --help
Traceback (most recent call last):
  File "/usr/local/bin/ggshield", line 5, in <module>
    from ggshield.cmd import cli_wrapper
  File "/usr/local/lib/python3.9/site-packages/ggshield/cmd.py", line 10, in <module>
    from ggshield.output import JSONHandler, OutputHandler, TextHandler
  File "/usr/local/lib/python3.9/site-packages/ggshield/output/__init__.py", line 1, in <module>
    from .json import JSONHandler
  File "/usr/local/lib/python3.9/site-packages/ggshield/output/json/__init__.py", line 1, in <module>
    from .json_output import JSONHandler
  File "/usr/local/lib/python3.9/site-packages/ggshield/output/json/json_output.py", line 8, in <module>
    from ggshield.output.output_handler import OutputHandler
  File "/usr/local/lib/python3.9/site-packages/ggshield/output/output_handler.py", line 3, in <module>
    from ggshield.scan import Result, ScanCollection
  File "/usr/local/lib/python3.9/site-packages/ggshield/scan/__init__.py", line 1, in <module>
    from .scannable import Commit, File, Files, Result, ScanCollection
  File "/usr/local/lib/python3.9/site-packages/ggshield/scan/scannable.py", line 11, in <module>
    from ggshield.config import CPU_COUNT, MAX_FILE_SIZE, Cache
  File "/usr/local/lib/python3.9/site-packages/ggshield/config.py", line 13, in <module>
    from .git_shell import get_git_root, is_git_dir
  File "/usr/local/lib/python3.9/site-packages/ggshield/git_shell.py", line 23, in <module>
    GIT_PATH = get_git_path(os.getcwd())
  File "/usr/local/lib/python3.9/site-packages/ggshield/git_shell.py", line 18, in get_git_path
    raise Exception("unable to find git executable in PATH/PATHEXT")
Exception: unable to find git executable in PATH/PATHEXT
```

The issue is here:

https://github.com/GitGuardian/gg-shield/blob/main/ggshield/git_shell.py#L17

```
git_path = str(which("git"))

if cwd in git_path and cwd not in os.environ.get("PATH", "").split(os.pathsep):
```

I'm not sure the history of that code but it seems overly complex as `which()` returns `None` if the executable is not found.

**Comment by Jguer** [comment]
Hey @rgajason I believe it's a fix for #27, I'll verify if it can be made more reliable

**Comment by rgajason** [comment]
FYI, with that patch `ggshield` will try and run even if `git` isn't installed.

```
$ ggshield --help
Usage: ggshield [OPTIONS] COMMAND [ARGS]...

Options:
  -c, --config-path FILE  Set a custom config file. Ignores local and global
                          config files.

  -v, --verbose           Verbose display mode.
  -h, --help              Show this message and exit.

Commands:
  ignore   Command to ignore some secrets.
  install  Command to install a pre-commit or pre-push hook (local or...
  scan     Command to scan various contents.
$ which git
/usr/bin/which: no git in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

(same behavior on Windows)

Is that the desired behavior?  Based on the verbiage of the error message it seems not, but I wanted to confirm.  I think I can put together an alternative test that addresses both situations.

**Comment by rgajason** [comment]
I opened https://github.com/GitGuardian/gg-shield/pull/53 with one possible solution.

Please let me know if you would like any edits.  There is a potential gap in the checking on case-insensitive filesystems but it would add complexity to the code to test for that scenario and potentially require creating a temp file/folder.  We could make assumptions based on the OS if you think the extra checking is worthwhile.

**Comment by Jguer** [comment]
Closing this as part of the merge of #53
